<?php

/**
 * @file
 *
 * Install file for the Ting visual relation module.
 */

/**
 * Implements hook_ding_entity_fields().
 */
/*function ting_visual_relation_ding_entity_fields() {
	return array(
		'ting_visual_relations' => array(
			'field' => array(
				'locked' => FALSE,
				'storage' => array(
					'type' => 'virtual_field',
				),
			),
			'instance' => array(
				'label' => t('Ting visual relations'),
			),
		),
	);
}*/
